# Generated by Django 5.0 on 2023-12-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_color_varient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorVarient',
            new_name='ColorVariant',
        ),
        migrations.RenameModel(
            old_name='SizeVarient',
            new_name='SizeVariant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='color_varient',
            new_name='color_variant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_varient',
            new_name='size_variant',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to='catgories'),
        ),
    ]
