# Generated by Django 5.0 on 2023-12-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_colorvarient_colorvariant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_variant',
        ),
    ]
